### ISSUE TITLE
Crash on iOS 9.3.5 (iPod touch)

### ISSUE THREAD

**Issue by CavalcanteLeo** [justindhill/DRPLoadingSpinner#2]
-[UICollectionView setRefreshControl:]: unrecognized selector sent to instance 0x15a51800

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UICollectionView setRefreshControl:]: unrecognized selector sent to instance 0x15a51800'

![captura de tela 2016-12-22 as 16 34 59](https://cloud.githubusercontent.com/assets/1735944/21436243/a9527308-c864-11e6-81bd-8168d6f75c76.png)

**Comment by justindhill** [comment]
This is actually due to the fact that you can't say refresh controls on scroll views before iOS 10. It will still work fine on table view controllers.

**Comment by justindhill** [comment]
Add*
